import json
from pathlib import Path

import numpy as np
import pytest

from neuroselect.official_v1_preprocessing import (
    CHANNEL_COUNT,
    NeuroSelectOfficialV1EventPreprocessing,
)


ROOT = Path(__file__).resolve().parents[1]
RAW_PATH = ROOT / "data/raw/spanishbcbl_s22/MEG/FIF/22_9788/231214/block1.fif"
REFERENCE_PATH = ROOT / "results/official_event_tensor_examples/trial_2_first_5.npz"
PARITY_PATH = ROOT / "results/eight_trial_official_v1_parity.json"
EVENTS = [
    (383.276, "l"),
    (383.451, "a"),
    (383.644, " "),
    (383.901, "t"),
    (383.985, "a"),
]


@pytest.fixture(scope="module")
def processor():
    if not RAW_PATH.exists() or not REFERENCE_PATH.exists():
        pytest.skip("official parity fixtures are unavailable")
    return NeuroSelectOfficialV1EventPreprocessing.from_raw(
        RAW_PATH,
        recording_start_seconds=308.0,
    )


def test_official_v1_matches_validated_trial_two_reference(processor):
    reference = np.load(REFERENCE_PATH)["official"]
    assert processor.signal.shape[1] == CHANNEL_COUNT
    assert tuple(processor.channel_names) == tuple(
        json.loads(Path(ROOT / "results/official_event_tensor_parity.json").read_text())[
            "channel_order"
        ]["official_extractor_header"]
    )
    for index, (timestamp, _label) in enumerate(EVENTS):
        result = processor.extract_event(timestamp)
        assert result.event_time_seconds == timestamp
        assert result.tensor.shape == (25, CHANNEL_COUNT)
        assert result.tensor.dtype == np.float32
        assert np.isfinite(result.tensor).all()
        np.testing.assert_allclose(result.tensor, reference[index], rtol=0.0, atol=1e-20)


def test_first_event_has_continuous_context_without_padding(processor):
    result = processor.extract_event(EVENTS[0][0])
    assert result.metadata["event_sample_index"] == 3764
    assert result.metadata["window_start_sample_index"] == 3754
    assert result.metadata["zero_padded"] is False
    assert result.tensor.shape == (25, CHANNEL_COUNT)


@pytest.mark.parametrize(
    "trial_number,event_index,timestamp,expected_hash,expected_window_start",
    [
        (3, 9, 396.790, "c5226ffaec2a57d581f8baeca6360f4a6659bb494989f3afb0db91ec38cc8814", 4430),
        (5, 10, 420.270, "3ff43a97570571281c9db47c6a368bf852542e077f13fa01d7b84495ea240921", 5604),
        (6, 2, 430.050, "b7c73309f3b78d1fe468bd13d1861ae9192032ef0a607a182a077c09292d04b7", 6093),
        (7, 19, 444.870, "3449e4a9196b0fdcaaca5bbf7646a6fe2cf8445ec94900ef95b18b0363ff8af5", 6834),
    ],
)
def test_four_overlap_regressions_match_independent_official_hashes(
    processor, trial_number, event_index, timestamp, expected_hash, expected_window_start
):
    """The four forensic references were generated by the pinned official extractor."""
    if not PARITY_PATH.exists():
        pytest.skip("eight-trial official parity reference is unavailable")
    parity = json.loads(PARITY_PATH.read_text(encoding="utf-8"))
    trial = next(row for row in parity["trial_identity_and_event_audit"] if row["trial_number"] == trial_number)
    reference = next(row for row in trial["events"] if row["event_index"] == event_index)
    assert reference["official_tensor"]["sha256"] == expected_hash
    result = processor.extract_event(timestamp)
    assert result.tensor.shape == (25, CHANNEL_COUNT)
    assert np.isfinite(result.tensor).all()
    assert result.metadata["window_start_sample_index"] == expected_window_start
    import hashlib

    assert hashlib.sha256(np.ascontiguousarray(result.tensor.T).tobytes()).hexdigest() == expected_hash


def test_historical_pipeline_remains_present_and_sentence_scoped():
    source = (ROOT / "scripts/prepare_real_subset.py").read_text(encoding="utf-8")
    assert "raw.copy().crop(tmin=start, tmax=end, include_tmax=False)" in source
    assert "data = data - data[:baseline_count].mean(axis=0, keepdims=True)" in source
    assert "data = np.clip(data, -5.0, 5.0)" in source
